alter table SPEEDYPIZZA2_CUSTOMER add constraint FK_SPEEDYPIZZA2_CUSTOMER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_SPEEDYPIZZA2_CUSTOMER_ON_USER on SPEEDYPIZZA2_CUSTOMER (USER_ID);
